user/models.py
from typing import TYPE_CHECKING
from sqlalchemy import Table, Column, Integer, String

if TYPE_CHECKING:
    from aiomysql.sa.connection import SAConnection

from db import metadata

user_table = Table(
    "user",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("username", String(15), index=True, unique=True),
    Column("password", String(128)),
    Column("image", String(45), nullable=True),
)


async def get_user_by_username(conn: "SAConnection", username: str) -> dict:
    user_query = user_table.select().where(user_table.c.username == username)
    user_row = await conn.fetch_one(query=user_query)

    if user_row:
        user_dict = dict(user_row)
    else:
        return {}

    return user_dict

home/views.py
from quart import Blueprint, session

home_app = Blueprint("home_app", __name__)


@home_app.route("/", methods=["GET"])
async def init() -> str:
    return "Hello " + str(session.get("username"))

user/views.py
from typing import TYPE_CHECKING
from quart import (
    Blueprint,
    render_template,
    request,
    session,
    current_app,
    flash,
    redirect,
    url_for,
)
from passlib.hash import pbkdf2_sha256
import uuid

if TYPE_CHECKING:
    from quart.wrappers.response import Response

from user.models import user_table, get_user_by_username

user_app = Blueprint("user_app", __name__)


@user_app.route("/register", methods=["GET", "POST"])
async def register() -> "Response":
    error: str = ""
    username: str = ""
    password: str = ""
    csrf_token: uuid.UUID = uuid.uuid4()

    if request.method == "GET":
        session["csrf_token"] = str(csrf_token)

    if request.method == "POST":
        form: dict = await request.form
        username = form.get("username", "")
        password = form.get("password", "")

        if not username or not password:
            error = "Please enter username and password"
        else:
            if (
                session.get("csrf_token") != form.get("csrf_token")
                and not current_app.testing
            ):
                error = "Invalid POST contents"

            conn = current_app.dbc

            # check if the user exists
            if not error:
                user = await get_user_by_username(conn, username)
                if user and user["id"]:
                    error = "Username already exists"

            # register the user
            if not error:
                if not current_app.testing:
                    del session["csrf_token"]

                hash: str = pbkdf2_sha256.hash(password)
                user_insert = user_table.insert().values(
                    username=username, password=hash
                )
                await conn.execute(query=user_insert)
                await flash("You have been registered, please login")
                return redirect(url_for(".login"))
            else:
                session["csrf_token"] = str(csrf_token)

    return await render_template(
        "user/register.html", error=error, username=username, csrf_token=csrf_token
    )


@user_app.route("/login", methods=["GET", "POST"])
async def login() -> "Response":
    error: str = ""
    username: str = ""
    password: str = ""
    csrf_token: uuid.UUID = uuid.uuid4()

    if request.method == "GET":
        session["csrf_token"] = str(csrf_token)
        if request.args.get("next"):
            session["next"] = request.args.get("next")

    if request.method == "POST":
        form: dict = await request.form
        username = form.get("username")
        password = form.get("password")

        if not username or not password:
            error = "Please enter username and password"
        else:
            if (
                session.get("csrf_token") != form.get("csrf_token")
                and not current_app.testing
            ):
                error = "Invalid POST contents"

        conn = current_app.dbc

        if not error:
            # check if the user exists
            user = await get_user_by_username(conn, form.get("username"))
            if not user:
                error = "User not found"
            # check the password
            elif not pbkdf2_sha256.verify(password, user.get("password")):
                error = "User not found"

        if not error:
            # login the user
            if not current_app.testing:
                del session["csrf_token"]

            session["user_id"] = user.get("id")
            session["username"] = user.get("username")

            if "next" in session:
                next = session.get("next")
                session.pop("next")
                return redirect(next)
            else:
                return redirect(url_for("home_app.init"))
        else:
            session["csrf_token"] = str(csrf_token)

    return await render_template(
        "user/login.html", error=error, username=username, csrf_token=csrf_token
    )


@user_app.route("/logout", methods=["GET"])
async def logout() -> "Response":
    del session["user_id"]
    del session["username"]
    return redirect(url_for(".login"))

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="widht=device-width, initial-sclae=1" />
        <title>{% block title %}{% endblock %}</title>

        <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" />

        {% block header %}{% endblock %}
    </head>
    <body>
        <div class="container">
            {% block content %}{% endblock %}

            <div class="col-md-offset-3 col-md-6">
                <hr />
                <footer>
                    &copy; copyright 2021 quartfeed
                </footer>
            </div>


        </div>

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="//code.jquery.com/jquery-1.12.1.min.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    </body>
</html>

templates/navbar.html
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{{ url_for("home_app.init") }}">QuartFeed</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                {% if session.username %}
                <li role="presentation" class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                      @{{ session.username }} <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="#">View profile</a></li>
                        <li><a href="#">Edit profile</a></li>
                    </ul>
                </li>
                <li>
                    <a href="{{ url_for("user_app.logout") }}" class="navbar-link">Logout</a></p>
                </li> 
                {% else %}
                <li>
                    <a href="{{ url_for("user_app.login") }}" class="navbar-link">Login</a></p>
                </li>     
                <li>
                    <a href="{{ url_for("user_app.register") }}" class="navbar-link">Register</a></p>
                </li> 
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/user/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}

{% block content %}

{% include "navbar.html" %}

<div id="flashed-messages">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-success">{{ message }}</div>
    {% endfor %}
</div>

<div class="row">

    <div class="col-md-offset-3 col-md-6">

        <h3>Login</h3>

        {% if error %}
        <div class="text-danger">{{ error }}</div>
        {% endif %}

        <form method="POST" action="{{ url_for('.login') }}" role="form">

            <div class="form-group">
                <label for="username">Username</label>
                <input name="username" type="text" class="form-control" id="username"
                    value="{% if username %}{{ username }}{% endif %}"
                    placeholder="Enter your username"
                />
            </div>

            <div class="form-group">
                <label for="password">Password</label>
                <input name="password" type="password" class="form-control" id="password" />
            </div>

            <input type="hidden" name="csrf_token" value="{{ csrf_token }}" />
            <button type="submit" class="btn btn-default">Login</button>

        </form>

    </div>

</div>

{% endblock %}

templates/user/register.html
{% extends "base.html" %} {% block title %}Registration{% endblock %}

{% block content %}

{% include "navbar.html" %}

<div class="row">
    <div class="col-md-offset-3 col-md-6">
        <h3>Registration</h3>
        
        {% if error %}
        <div class="alert alert-danger" role="alert">{{ error }}</div>
        {% endif %}

        <form method="POST" action="{{ url_for('.register') }}" role="form">

            <div class="form-group">
                <label for="username">Username</label>
                <input name="username" type="text" class="form-control" id="username"
                    value="{% if username %}{{ username }}{% endif %}"
                    placeholder="Select a username" />
            </div>

            <div class="form-group">
                <label for="password">Password</label>
                <input name="password" type="password" class="form-control" id="password"
                    placeholder="Password" />
            </div>

            <input type="hidden" name="csrf_token" value="{{ csrf_token }}" />
            <button type="submit" class="btn btn-default">Register</button>
            
        </form>
    </div>
</div>


{% endblock %}